### PR TITLE
id-3434: severity aggregation properly takes max of severity levels

### PR DESCRIPTION
**Pull request by equinor-ruaj**
* Fixed severity aggregation.
* Fixed severity aggregation test. Test fails on old aggregation code. Test passes now.

### CODE REVIEW

**Comment by equinor-ruaj** [comment]
Build fails due to opencensus dependency.

**Comment by equinor-ruaj** [comment]
BEFORE MERGING: After https://github.com/equinor/ioc-hierarchy-service/pull/33 has been merged.
Update this branch with changes in master for build to pass. (Changes remove opencensus library)

**Comment by equinor-ruaj** [comment]
> BEFORE MERGING: After #33 has been merged. Update this branch with changes in master for build to pass. (Changes remove opencensus library)

Required changes merged, ready for review @pettermk

**Review by pettermk — APPROVED** [review]
:+1:

**Pull request merged**
